pipeline{
    agent any
    
    stages{
        stage("Fetch Git repo") {
            steps {
                git branch: 'main', credentialsId: '6f0c0be8-081e-46bb-9129-c98f5b5f7a65', url: 'git@github.com:plavy/sosa.git'
            }
        }
        stage("Test") {
            steps {
                dir("lab3") {
                    sh "docker build . -t app"
                    sh "docker run --env PERFORM_TEST=unittest -t app"
                    // sh "python -m unittest > /home/jenkins/cicd/logs/\$(date '+%F-%T')-unittest"
                }
            }
        }
        stage("Deploy") {
            steps {
                dir("lab3") {
                    sh "docker build ."
                }
            }
        }
    }
}