pipeline{
    agent any
    
    stages{
        stage("Fetch Git repo") {
            steps {
                git branch: 'main', credentialsId: '6f0c0be8-081e-46bb-9129-c98f5b5f7a65', url: 'git@github.com:plavy/sosa.git'
            }
        }
        stage("Test") {
            steps {
                dir("lab3") {
                    sh "docker build ."
                    sh "python -m unittest > /home/jenkins/cicd/logs/\$(date +%s)-unittest"
                    sh "bandit -r . > /home/jenkins/cicd/logs/\$(date +%s)-bandit"
                }
            }
        }
        stage("Deploy") {
            steps {
                dir("lab3") {
                    sh "ls -l"
                }
            }
        }
    }
}